version: '3'

services:
  backend:
    container_name: backend
    image: payrollsystem/backend
    build: ./payrollsystem
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    volumes:
      - ./payrollsystem:/app
    restart: always
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - "postgres_data:/var/lib/postgresql/data/"
    ports:
      - "5432:5432"
    restart: on-failure

  redis:
    container_name: redis
    image: redis:alpine
    restart: always


  celery:
    image: "celery:latest"
    container_name: celery
    command: >
      sh -c "celery worker -l info  &&
      celery beat -l info"
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    links:
      - redis
    depends_on:
      - redis

volumes:
  postgres_data:
