# Generated by Django 4.1.4 on 2024-04-18 21:57

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('type', models.IntegerField(choices=[(1, 'income'), (2, 'deficit'), (3, 'increment')])),
                ('date', models.DateField(default=datetime.date(2024, 4, 18))),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_incomes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('date', models.DateField(db_index=True, default=datetime.date(2024, 4, 18), unique=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_incomes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
